# Generated by Django 5.1.4 on 2025-01-08 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Personal Care', 'Personal Care'), ('Debt Payments', 'Debt Payments'), ('Savings & Investments', 'Savings & Investments'), ('Gifts & Donations', 'Gifts & Donations'), ('Insurance', 'Insurance'), ('Travel', 'Travel'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
