site_name: Python Documentation
site_dir: _site
docs_dir: docs
repo_url: "https://github.com/manunmathew/python"
repo_name: "GitHub"
nav:
  - Home: index.md
  - Basics:
      - Assignment: Basics/assignment.md
      - Basics: Basics/basics.md
      - Conditional Statements: Basics/conditional_statements.md
      - Formatters: Basics/formatters.md
      - Python Operators: Basics/python_operators.md
      - User Input: Basics/userinput.md
  - Data Types:
      - Dictionaries Operations: DataTypes/DictionariesOperations.md
      - List Operations: DataTypes/ListOperations.md
      - Set Operations: DataTypes/SetOperations.md
      - Special Numbers Guide: DataTypes/SpecialNumbersGuide.md
      - String Formatting: DataTypes/StringFormating.md
      - String Operations: DataTypes/StringOperations.md
      - Tuple Operations: DataTypes/TupleOperations.md
  - Functions:
      - Lambda: Functions/Lambda.md
      - List Comprehension: Functions/ListComprehension.md
      - Recursion: Functions/Recursion.md
      - Functions: Functions/functions.md
  - OOP Concepts:
      - Abstraction: OOPsConcepts/Abstraction.md
      - Encapsulation: OOPsConcepts/Encapsulation.md
      - Polymorphism: OOPsConcepts/Polymorphism.md
      - Python OOP Concepts: OOPsConcepts/PythonOOPsConcepts.md
  - Exceptions Handling:
      - Assertion Exception: ExceptionsHandling/AssertionException.md
      - Exception Handling: ExceptionsHandling/ExceptionsHandling.md
  - Looping Statements:
      - Looping Statements: LoopingStatements/loopingstatements.md
  - Modules:
      - Modules Overview: Modules/Modules.md
      - OS Module vs Native Commands: Modules/os_module_vs_native_commands.md
  - Regular Expressions:
      - Regular Expressions: RegularExpressions/RegEx.md
  - SQL:
      - Python to SQL: PythonToSQL/PythonToSQL.md
      - SQL: SQL/sql.md
  - File Handling:
      - Python File Handling: FileHandling/PythonFileHandling.md
  - HTML:
      - HTML Introduction: HTML/overview.md
      - HTML Tags: HTML/common_tags.md
      - HTML Lists: HTML/html_lists.md
      - HTML Tables: HTML/html_tables.md
      - HTML Forms: HTML/html_form.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.instant
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.links
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: deep-purple
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: deep-purple
    accent: purple
  markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - meta
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: tag:yaml.org,2002:python/name:materialx.emoji.twemoji
      emoji_generator: tag:yaml.org,2002:python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
