site_name: Python Documentation
site_dir: _site
docs_dir: docs
site_url: "https://manunmathew.github.io/python"
repo_url: "https://github.com/manunmathew/python"
repo_name: "GitHub"
nav:
  - Home: index.md
  - Python:
    - Basics:
        - Assignment: Python/Basics/assignment.md
        - Basics: Python/Basics/basics.md
        - Conditional Statements: Python/Basics/conditional_statements.md
        - Formatters: Python/Basics/formatters.md
        - Python Operators: Python/Basics/python_operators.md
        - User Input: Python/Basics/userinput.md
    - Data Types:
        - Dictionaries Operations: Python/DataTypes/DictionariesOperations.md
        - List Operations: Python/DataTypes/ListOperations.md
        - Set Operations: Python/DataTypes/SetOperations.md
        - Special Numbers Guide: Python/DataTypes/SpecialNumbersGuide.md
        - String Formatting: Python/DataTypes/StringFormating.md
        - String Operations: Python/DataTypes/StringOperations.md
        - Tuple Operations: Python/DataTypes/TupleOperations.md
    - Functions:
        - Lambda: Python/Functions/Lambda.md
        - List Comprehension: Python/Functions/ListComprehension.md
        - Recursion: Python/Functions/Recursion.md
        - Functions: Python/Functions/functions.md
    - OOP Concepts:
        - Abstraction: Python/OOPsConcepts/Abstraction.md
        - Encapsulation: Python/OOPsConcepts/Encapsulation.md
        - Polymorphism: Python/OOPsConcepts/Polymorphism.md
        - Python OOP Concepts: Python/OOPsConcepts/PythonOOPsConcepts.md
    - Exceptions Handling:
        - Assertion Exception: Python/ExceptionsHandling/AssertionException.md
        - Exception Handling: Python/ExceptionsHandling/ExceptionsHandling.md
    - Looping Statements:
        - Looping Statements: Python/LoopingStatements/loopingstatements.md
    - Modules:
        - Modules Overview: Python/Modules/Modules.md
        - OS Module vs Native Commands: Python/Modules/os_module_vs_native_commands.md
    - Regular Expressions:
        - Regular Expressions: Python/RegularExpressions/RegEx.md
    - File Handling:
        - Python File Handling: Python/FileHandling/PythonFileHandling.md
  - SQL:
      - Python to SQL: SQL/PythonToSQL/PythonToSQL.md
      - SQL: SQL/sql.md
  - HTML:
      - HTML Introduction: HTML/overview.md
      - HTML Tags: HTML/common_tags.md
      - HTML Lists: HTML/html_lists.md
      - HTML Tables: HTML/html_tables.md
      - HTML Forms: HTML/html_form.md
      - HTML Div: HTML/div.md
  - CSS:
      - CSS Introduction: CSS/css.md
      - CSS Selectors: CSS/Selectors.md
      - CSS Box Model: CSS/CSSBoxModel.md
      - CSS AOS: CSS/aos.md
  - Bootstrap:
      - Bootstrap Introduction: Bootstrap/introduction.md
      - Bootstrap Responsive Screen: Bootstrap/Responsive.md
      - Bootstrap Components: Bootstrap/components.md
  - Django:
      - Django Introduction: Django/introduction.md
      - Django Project: Django/projects.md
      - Django App: Django/app.md
      - Django Model: Django/model.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.instant
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.links
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: deep-purple
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: deep-purple
    accent: purple
  markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - meta
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: tag:yaml.org,2002:python/name:materialx.emoji.twemoji
      emoji_generator: tag:yaml.org,2002:python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
