# Generated by Django 5.1.3 on 2024-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Travel', 'Travel'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('HealthCare', 'HealthCare'), ('Miscellaneous', 'Miscellaneous')], default='Food', max_length=200)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'CASH')], default='CASH', max_length=200)),
                ('priority', models.CharField(choices=[('NEED', 'NEED'), ('WANT', 'WANT')], default='NEED', max_length=200)),
            ],
        ),
    ]
