# Generated by Django 5.1.3 on 2024-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('Answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Multi_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('Answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('Answer', models.IntegerField()),
            ],
        ),
    ]
