# Generated by Django 5.1.3 on 2024-11-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0003_circlearea_model_trianglearea_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCreate_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=20)),
            ],
        ),
    ]
