# Generated by Django 5.1.3 on 2024-11-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_filmcreate_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmcreate_model',
            old_name='name',
            new_name='films_name',
        ),
    ]
